// Report export helpers (CSV + PDF).
// PDF uses the browser print dialog against a styled printable window — no
// heavyweight PDF lib needed for the W1 prototype.

export type CsvRow = Record<string, string | number | null | undefined>;

function escapeCsv(value: string | number | null | undefined): string {
	const s = value == null ? "" : String(value);
	if (/[",\n]/.test(s)) {
		return `"${s.replace(/"/g, '""')}"`;
	}
	return s;
}

export function toCsv(rows: CsvRow[], headers?: string[]): string {
	if (rows.length === 0) return headers ? headers.join(",") : "";
	const cols = headers ?? Object.keys(rows[0] as CsvRow);
	const lines = [cols.join(",")];
	for (const row of rows) {
		lines.push(cols.map((c) => escapeCsv(row[c])).join(","));
	}
	return lines.join("\n");
}

export function downloadCsv(
	filename: string,
	rows: CsvRow[],
	headers?: string[],
) {
	const csv = toCsv(rows, headers);
	const blob = new Blob([`﻿${csv}`], {
		type: "text/csv;charset=utf-8;",
	});
	triggerDownload(
		blob,
		filename.endsWith(".csv") ? filename : `${filename}.csv`,
	);
}

function triggerDownload(blob: Blob, filename: string) {
	const url = URL.createObjectURL(blob);
	const a = document.createElement("a");
	a.href = url;
	a.download = filename;
	document.body.appendChild(a);
	a.click();
	document.body.removeChild(a);
	URL.revokeObjectURL(url);
}

export interface PdfTable {
	columns: string[];
	rows: (string | number)[][];
}

/**
 * Opens a print-ready window and invokes the browser print dialog. The user
 * can "Save as PDF" from there. Good enough for a W1 report export.
 */
export function printReport(
	title: string,
	subtitle: string,
	summary: { label: string; value: string }[],
	table: PdfTable,
) {
	const win = window.open("", "_blank", "width=900,height=1000");
	if (!win) return;

	const summaryHtml = summary
		.map(
			(s) =>
				`<div class="sum"><div class="sum-label">${s.label}</div><div class="sum-value">${s.value}</div></div>`,
		)
		.join("");

	const head = table.columns.map((c) => `<th>${c}</th>`).join("");
	const body = table.rows
		.map((r) => `<tr>${r.map((cell) => `<td>${cell}</td>`).join("")}</tr>`)
		.join("");

	win.document.write(`<!doctype html><html><head><meta charset="utf-8" />
<title>${title}</title>
<style>
  * { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
  body { margin: 40px; color: #14261f; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .sub { color: #6b7d74; margin: 0 0 24px; font-size: 13px; }
  .summary { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 28px; }
  .sum { border: 1px solid #e6ede8; border-radius: 12px; padding: 12px 18px; min-width: 150px; }
  .sum-label { font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: #6b7d74; }
  .sum-value { font-size: 20px; font-weight: 700; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; background: #eef7f2; padding: 8px 10px; border-bottom: 2px solid #d6ecdf; }
  td { padding: 7px 10px; border-bottom: 1px solid #eef2ef; }
  tr:nth-child(even) td { background: #fafcfa; }
  .foot { margin-top: 28px; font-size: 11px; color: #93a29a; }
</style></head><body>
  <h1>${title}</h1>
  <p class="sub">${subtitle}</p>
  <div class="summary">${summaryHtml}</div>
  <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>
  <p class="foot">Generated by 611 Petty Cash — ${new Date().toLocaleString()}</p>
</body></html>`);
	win.document.close();
	win.focus();
	setTimeout(() => win.print(), 350);
}
